[package]
name = "car-ai"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libm = "0.2.5"
macroquad = "0.3.23"
num-traits = { version = "0.2", default-features = false, features = ["libm"] }
